### ISSUE TITLE
[CWS] Missing endcaps when stroking straight lines

### ISSUE THREAD

**Issue by ctrlcctrlv** [MFEK/stroke#20]
![image](https://user-images.githubusercontent.com/838783/132395182-aff46ffc-ebf3-4331-ac0d-593bd1870802.png)

```
$ MFEKstroke CWS -i F_.glif -o F__guidelines.glif -w 30
```

# `F__guidelines.glif`
```xml
<?xml version='1.0' encoding='UTF-8'?>
<glyph name="F" format="2">
  <advance width="599"/>
  <unicode hex="0046"/>
  <anchor x="537" y="650" name="top"/>
  <outline>
    <contour>
      <point x="0" y="264" type="line"/>
      <point x="599" y="264" type="line"/>
    </contour>
  </outline>
</glyph>
```

**Comment by MatthewBlanchard** [comment]
I can't isolate this in the stroke code, and recreating the input as best I can in the editor I can't get it to do this.

Also the output is doubled in this example. I'm still working on the cause should have something tonight.

**Comment by MatthewBlanchard** [comment]
Figured out the issue. This glyph doesn't have a MOVE point as it's first point type, and so it's being interpreted as a closed path. The one 'cap' you see is actually a join.
